### ISSUE TITLE
Pricing Table

### ISSUE THREAD

**Issue by james-cordeiro** [Roadcert/roadcert.github.io#6]
I like this pricing table - free CSS - try to use but keep to material theme as well. The dark bit goes well with the APP interface. Inspect the source for the CSS.

https://graygrids.com/demos/snippets/startup-fw-pricing-table/

In addition, this one is also nice: https://shapebootstrap.net/item/1524967-flat-pricing-table-bootstrap-3-0 - attention to detail is something I'd like you to think about more. Notice how the coloured pricing table is bigger. 
- [ ] Only 3 pricing tables needed
- [ ] the 4th one which is currently the enquiry one needs just a small paragraph to contact us for more detail and quotations. This is when it is 100 vehicles or more. text is "Operating a fleet with 100 vehicles or more? We offer bigger and more bespoke plans also. Contact us for more detail"
- [ ] Use clean modern large thin typography and highlight keywords in the "4th price paragraph" with abbr tags and code tags creating modern look, feel and attention to ket messages.

**Comment by james-cordeiro** [comment]
Nice looking pricing tables here....

https://www.freshdesignweb.com/free-css-tables/

http://codepen.io/warzone246/pen/yiHns  ---- Actually this one is very nice. Go with this one and change to the traffic light colours. This is good as it offers nice tables with a long list of features.

**Comment by Freddie2015** [comment]
Use current pricing table. Add two more sections - one is below that spans across detailing up to 100. Then underneath it should be a contact us for "are you operating 100+ vehicles" then contact us directly.
